/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;
import java.util.Random;
import java.awt.Color;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class ClientForm extends javax.swing.JFrame {

    Cliente refCliente;
    

    public void setRefCliente(Cliente refCliente) {
        this.refCliente = refCliente;
    }

    
    public void addMensaje(String msj)
    {
        txaMensajes.append(msj + "\n");
    }  
    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaMensajes = new javax.swing.JTextArea();
        btnCrear = new javax.swing.JButton();
        nmVuelos = new javax.swing.JSpinner();
        btnCrearMa = new javax.swing.JButton();
        jcomTiempo = new javax.swing.JComboBox<>();
        jcomTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txaMensajes.setColumns(20);
        txaMensajes.setRows(5);
        jScrollPane1.setViewportView(txaMensajes);

        btnCrear.setText("Crear vuelos aleatorios");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCrearMa.setText("Crear vuelo");
        btnCrearMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMaActionPerformed(evt);
            }
        });

        jcomTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A tiempo", "Atrasado" }));
        jcomTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomTiempoActionPerformed(evt);
            }
        });

        jcomTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carga", "Pasajeros", "Privados" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearMa)
                    .addComponent(jcomTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nmVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcomTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcomTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearMa)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(nmVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            int value = (Integer) nmVuelos.getValue();
            if (value <= 0)
                JOptionPane.showMessageDialog(this, "El número tiene que ser mayor a 0");
            else{
                refCliente.hiloCliente.writer.writeInt(2);
                refCliente.hiloCliente.writer.writeUTF(nmVuelos.getValue().toString());
                Random rand = new Random();
                for (int i = 0;i < value;i++){
                    refCliente.hiloCliente.writer.writeInt(3);
                    refCliente.hiloCliente.writer.writeInt(rand.nextInt(3));
                    refCliente.hiloCliente.writer.writeInt(rand.nextInt(2));
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se puede");
        }
        
        
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCrearMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMaActionPerformed
        try {
            refCliente.hiloCliente.writer.writeInt(2);
            refCliente.hiloCliente.writer.writeUTF("1");
            refCliente.hiloCliente.writer.writeInt(3);
            refCliente.hiloCliente.writer.writeInt(jcomTipo.getSelectedIndex());
            refCliente.hiloCliente.writer.writeInt(jcomTiempo.getSelectedIndex());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnCrearMaActionPerformed

    private void jcomTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomTiempoActionPerformed

    public void pintarPartidaIniciada(){

    }
    
    
    public void pintarDados(int v1, int v2, String user){

        
    }
    
    public void pintarSiguienteTurno(String user){

    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrear;
    public javax.swing.JButton btnCrearMa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcomTiempo;
    private javax.swing.JComboBox<String> jcomTipo;
    private javax.swing.JSpinner nmVuelos;
    private javax.swing.JTextArea txaMensajes;
    // End of variables declaration//GEN-END:variables


}
